<a href="https://colab.research.google.com/github/satishgc227/Derby-project/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# -*- coding: utf-8 -*-
"""Kmeans,PCA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/satishgc227/Derby-project/blob/main/Kmeans%2CPCA.ipynb
"""

# Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
# Load in the data
df = pd.read_csv('/content/edited complete.csv',encoding='latin',nrows=100000)

df['race_type\xa0'].unique()
df['course_type'].unique()
df['track_condition\xa0'].unique()
df['track_id'].unique()

s=df[['race_type\xa0','course_type','track_condition\xa0','track_id']]

ohe=OneHotEncoder()
feature_array=ohe.fit_transform(df[['race_type\xa0','course_type','track_condition\xa0','track_id']]).toarray()

feature_labels=ohe.categories_
print(feature_labels)

np.hstack(feature_labels)

feature_labels=np.hstack(feature_labels)
f=pd.DataFrame(feature_array,columns=feature_labels)
pd.concat([df,f],axis=1)

df.drop(['race_date','track_id','course_type','track_condition\xa0','race_type\xa0','jockey\xa0','program_number\xa0'],axis=1,inplace=True)
df=pd.concat([df,f],axis=1)

df.isnull().any()



"""Removing the null values"""

df.replace([np.inf,-np.inf],np.nan ,inplace=True)
df.dropna(inplace=True)
df.isnull().any()

!pip install movecolumn
import movecolumn as mc
mc.MoveToLast(df,'position_at_finish\xa0')

X = df.iloc[:,:-1]
y = df.iloc[:, -1]



/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


[array(['ALW', 'AOC', 'CLM', 'SOC', 'SST', 'STK', 'STR', 'WCL'],
      dtype=object), array(['D', 'I', 'M', 'O', 'T'], dtype=object), array(['FM ', 'FT ', 'GD ', 'MY ', 'SY ', 'YL '], dtype=object), array(['AQU', 'BEL', 'SAR'], dtype=object)]
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for movecolumn: filename=movecolumn-0.0.7-py3-none-any.whl size=10440 sha256=fc12b0e7e435c6c8c8f3b8ac809111e77a1719598bf794955b93d1f67625d051
  Stored in directory: /root/.cache/pip/wheels/4c/ad/b7/671cd4a6e1464bb816aea3bacdcc933acf25e3d47946a7edcf
Successfully built movecolumn


0        8
1        8
2        8
3        8
4        8
        ..
99995    6
99996    6
99997    6
99998    6
99999    6
Name: position_at_finish , Length: 100000, dtype: int64

In [27]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA
pca = PCA(n_components=10)
X = pca.fit_transform(X)
X
#df=pd.concat([df,pd.DataFrame(X)],axis=1)
#df.columns
X.shape

(100000, 10)

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state = 1)
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

knn_clf=KNeighborsClassifier()
knn_clf.fit(X_train,y_train)
ypred=knn_clf.predict(X_test)

In [31]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, ypred)
print(result)
print(result)
result1 = classification_report(y_test, ypred)
print(result1)
print (result1)
result2 = accuracy_score(y_test,ypred)
print(result2)


[[1992    0    0    0    0    0    0    0    0    0    0]
 [   0 2573    0    0    0    0    0    0    0    0    0]
 [   0    0 2353    0    0    0    0    0    0    0    0]
 [   0    0    0 2364    0    0    0    0    0    0    0]
 [   0    0    0    0 2993    0    0    0    0    0    0]
 [   0    0    0    0    0 3459    0    0    0    0    0]
 [   0    0    0    0    0    0 1648    0    0    0    0]
 [   0    0    0    0    0    0    0 1448    0    0    0]
 [   0    0    0    0    0    0    0    0  639    0    0]
 [   0    0    0    0    0    0    0    0    0  400    0]
 [   0    0    0    0    0    0    0    0    0    0  131]]
[[1992    0    0    0    0    0    0    0    0    0    0]
 [   0 2573    0    0    0    0    0    0    0    0    0]
 [   0    0 2353    0    0    0    0    0    0    0    0]
 [   0    0    0 2364    0    0    0    0    0    0    0]
 [   0    0    0    0 2993    0    0    0    0    0    0]
 [   0    0    0    0    0 3459    0    0    0    0    0]
 [   0    0  